/**
 * @license Copyright (c) 2003-2015, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

/* exported CKBUILDER_CONFIG */

var CKBUILDER_CONFIG = {
	skin: 'moono',
	languages: {'zh': 1, 'en': 1},
	ignore: [
		'bender.js',
		'.bender',
		'bender-err.log',
		'bender-out.log',
		'dev',
		'docs',
		'.DS_Store',
		'.editorconfig',
		'.gitignore',
		'.gitattributes',
		'gruntfile.js',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'less',
		'.mailmap',
		'node_modules',
		'package.json',
		'README.md',
		'tests'
	],
	plugins: {
		a11yhelp: 1,
		autogrow: 1,
		basicstyles: 1,
		clipboard: 1,
		colorbutton: 1,
		contextmenu: 1,
		confighelper: 1,
		elementspath: 1,
		enterkey: 1,
		entities: 1,
		filebrowser: 1,
		floatingspace: 1,
		font: 1,
		format: 1,
		horizontalrule: 1,
		htmlwriter: 1,
		iframe: 1,
		image: 1,
		image2: 1,
		indentlist: 1,
		indentblock: 1,
		justify: 1,
		link: 1,
		list: 1,
		liststyle: 1,
		pastefromword: 1,
		pastetext: 1,
		removeformat: 1,
		showborders: 1,
		smiley: 1,
		sourcearea: 1,
		stylescombo: 1,
		tab: 1,
		table: 1,
		tabletools: 1,
		toolbar: 1,
		undo: 1,
		uploadimage: 1,
		wysiwygarea: 1
	}
};
